server:
  port: 8781
spring:
  application:
    name: BASKET-SERVICE
resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  ratelimiter:
    instances:
      productService:
        limitForPeriod: 1
        limitRefreshPeriod: 1m