server:
  port: 8081
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
